# Generated by Django 5.0.3 on 2024-03-28 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='women',
            old_name='cat',
            new_name='cat_id',
        ),
    ]
