# Generated by Django 5.0.3 on 2024-03-28 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_rename_cat_women_cat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='women',
            old_name='cat_id',
            new_name='cat',
        ),
    ]
